version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: config/dev.Dockerfile
    image: palaute_dev
    volumes:
      - ./:/usr/src/app
      - nodemod:/usr/src/app/node_modules/
    ports:
      - 3000:3000
    container_name: palaute_dev

volumes:
  nodemod:
