version: '3.5'

services:
  app:
    build:
      context: ./
      dockerfile: dev.Dockerfile
    image: palaute_dev
    volumes:
      - ./:/usr/src/app
      # - nodemod:/usr/src/app/node_modules/
    environment:
      - POSTGRES_HOST=db
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DATABASE=postgres
      - REDIS_HOST=redis
      - JWT_KEY=minttujam
    ports:
      - 3000:3000
      - 9229:9229
    container_name: palaute_dev
  db:
    image: postgres:13.2
    environment:
      - PGDATA=/data
      - POSTGRES_PASSWORD=postgres
    ports:
      - 5432:5432
    volumes:
      - pg_data:/data
    container_name: palaute_db
  redis:
    image: redis:6.2.6
    command: redis-server
    container_name: palaute_redis

volumes:
  # nodemod:
  pg_data:
