name: Release 

on:
  push:
    branches: 
      - master

jobs:
  dockerhub-release: 
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2 

    - name: Login to DockerHub
      uses: docker/login-action@v1 
      with: 
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
            
    - name: Build and push
      uses: docker/build-push-action@v2
      with:
        push: true
        tags: toska/palaute:latest
        build-args: BASE_PATH=/palaute

  sentry-release:
    runs-on: ubuntu-latest
    needs: dockerhub-release
    steps:
    - uses: actions/checkout@v2

    - uses: actions/setup-node@v2
      with:
        node-version: '14'

    - name: Build frontend
      run: npm ci && npm run build

    - name: Create Sentry release
      uses: getsentry/action-release@v1
      env:
        SENTRY_URL: ${{ secrets.SENTRY_URL }}
        SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
        SENTRY_ORG: ${{ secrets.SENTRY_ORG }}
        SENTRY_PROJECT: ${{ secrets.SENTRY_PROJECT }}
      with:
        environment: production
        sourcemaps: './build/static/js'
